name: Deploy Infrastructure

on:
  push:
    branches:
      - develop

jobs:
  tf_fmt:
    name: Deploy terraform
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v1

    - name : Setup Terraform
      uses : hashicorp/setup-terraform@v1

    - name : Terraform init
      run : terraform init


    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions/apply@v0.4.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TF_ACTION_WORKING_DIR: 'terraform'
        AWS_ACCESS_KEY_ID:  ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY:  ${{ secrets.SECRET_KEY }}

    - name: Sync S3
      uses: jakejarvis/s3-sync-action@master
      env:
        SOURCE_DIR: 'refs/heads/develop'
        AWS_REGION: 'eu-central-1'
        AWS_S3_BUCKET: 'terraformbucket00101'
        AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
